repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-json
        exclude: ^viewer/tsconfig\.json$   # allows comments
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=512"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^extract/
      - id: ruff-format
        files: ^extract/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^viewer/src/.*\.(ts|tsx|css)$
